# Generated by Django 5.1.6 on 2025-02-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_excercise_workout_set_excercise_workout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excercise',
            new_name='Exercise',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='excercise',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='excercise',
            new_name='exercise',
        ),
    ]
