# Generated by Django 5.1.6 on 2025-02-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_excercise_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
